---
title: "data.frames I"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot[RO,RE]{Ogle (Nunavut, 6-9 Aug 2016)}
- \fancyfoot[LE,LO]{data.frames I}
output: pdf_document
geometry: left=0.5in, right=0.5in, top=0.5in, bottom=0.75in
---

```{r echo=FALSE, results='hide'}
source("../knitr_setup.R")
```

----

\vspace{-30pt}
# Preliminaries
\vspace{-12pt}
## Load Necessary Packages
\vspace{-12pt}
```{r results='hide', warning=FALSE, message=FALSE}
library(FSA)    # for headtail()
library(readxl) # for read_excel()
library(dplyr)  # for mutate()
```


\vspace{-16pt}
## Set Working Directory
\vspace{-12pt}
```{r eval=FALSE}
# Set your working directory to where your external data files (and scripts) are located.
setwd("C:/aaaWork/Web/GitHub/RcourseNunavut2016/Handouts")
```
\vspace{-18pt}

----

\vspace{-24pt}
# Load Data from External CSV File
\vspace{-18pt}
```{r R.options=list(max.print=72)}
dSC <- read.csv("SawyerCo_reduced.csv")
str(dSC)
headtail(dSC)
dSC$len
dSC$len[1]
dSC$len[c(1,3,5)]
```

\vspace{-24pt}

----

# Load Data from External Excel File
## Demonstrate A Mess
```{r echo=-c(1:3,9),error=TRUE, warning=FALSE}
################################################################################
# This is used to demonstrate problems with loading the Nunavut data as given
# to Derek Ogle.  See the next chunk for a better method.
tmp <- read_excel("PG027.SA.Data.xlsx")
str(tmp,list.len=10)          # list.len only used to save space
tmp$Index[1:10]               # positions used simply to limit output length
tmp$Location - Name[1:10]
tmp$'Location - Name'[1:10]
################################################################################
```

\newpage
## An Alternative -- More Work, But More Useful Result
\vspace{-12pt}
```{r warning=FALSE}
# Get new names and defined data types
( meta <- read.csv("PG027.SA_metadata.csv",stringsAsFactors=FALSE) )
# Now read the data
dNU <- read_excel("PG027.SA.Data.xlsx",na="nd",skip=1,
                  col_names=meta$new_names,col_types=meta$new_types)
str(dNU)
```
```{r}
# Adjust types of some variables
dNU <- mutate(dNU,netset.time=format(netset.time,"%T"),netlift.time=format(netlift.time,"%T"),
              fyear=factor(year),loc=factor(loc),locAKA=factor(locAKA),water.type=factor(water.type),
              spec=factor(spec),sex=factor(sex),mat=factor(mat),life.hist=factor(life.hist))
dNU <- as.data.frame(dNU)
str(dNU)
```
```{r R.options=list(max.print=72)}
dNU$loc
```


```{r echo=FALSE, results="hide", message=FALSE}
purl2("DataFrames1.Rmd",moreItems="knitr",out.dir="../Scripts",topnotes="Nunavut 6-9-Aug-16")
```
