---
title: "data.frames II"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot[RO,RE]{Ogle (Nunavut, 6-9 Aug 2016)}
- \fancyfoot[LE,LO]{data.frames II}
output: pdf_document
geometry: left=0.5in, right=0.5in, top=0.5in, bottom=0.75in
---

```{r echo=FALSE, results='hide'}
source("../knitr_setup.R")
```

----

# Preliminaries
## Load Necessary Packages
```{r results='hide', warning=FALSE, message=FALSE}
library(FSA)    # for headtail(), filterD(), lencat(), mapvalues(), 
library(dplyr)  # for select(), mutate(), filter()
```

## Load Data from External CSV File
```{r}
# Set your working directory to where your external data files (and scripts) are located.
setwd("C:/aaaWork/Web/GitHub/RcourseNunavut2016/Handouts")
dSC <- read.csv("SawyerCo_reduced.csv")
str(dSC)
headtail(dSC,n=6)
```

----

\newpage
# Select or Remove Variables from a data.frame

```{r}
dSC <- select(dSC,-age_strux,-lennote)
headtail(dSC)
```

----

# Add Variables to a data.frame
\vspace{-8pt}
```{r}
dSC <- mutate(dSC,len.in=len/25.4)
headtail(dSC)
```

```{r}
dSC <- mutate(dSC,lcat10=lencat(len,w=10))
headtail(dSC)
```

```{r}
dSC <- mutate(dSC,newspec=mapvalues(species,from=c("Walleye","Muskellunge"),to=c("WAE","MUE")))
headtail(dSC)
```

```{r}
dSC <- select(dSC,-(len.in:newspec))
headtail(dSC,n=2)
```

----

# Filter or Subset a data.frame
## Conditionally Select Individuals
```{r}
levels(dSC$waterbody)
dSC_chip <- filter(dSC,waterbody=="CHIPPEWA RIVER")
levels(dSC_chip$waterbody)
dSC_chip <- filterD(dSC,waterbody=="CHIPPEWA RIVER")
levels(dSC_chip$waterbody)
dSC_rivers <- filterD(dSC,waterbody %in% c("CHIPPEWA RIVER","NAMEKAGON RIVER"))
levels(dSC_rivers$waterbody)
levels(dSC_rivers$gear)
dSC_rivers <- filterD(dSC_rivers,gear!="BOTTOM GILL NET")
levels(dSC_rivers$gear)
levels(dSC_rivers$species)
dSC_rivers_trout <- filterD(dSC_rivers,species %in% c("Brook Trout","Brown Trot"))
levels(dSC_rivers_trout$species)
dSC_rivers_trout <- filterD(dSC_rivers,species %in% c("Brook Trout","Brown Trout"))
levels(dSC_rivers_trout$species)
tmp <- filterD(dSC_rivers_trout,len>=100 & len<200)
headtail(tmp)
tmp <- filterD(dSC_rivers_trout,len<100 | len>200)
headtail(tmp)
( bigBrowns <- filterD(dSC_rivers_trout,species=="Brown Trout",mon %in% c("Jul","Aug"),len>=500) )
( bigBrowns_nowt <- filterD(bigBrowns,is.na(weight)) )
( bigBrowns_wghd <- filterD(bigBrowns,!is.na(weight)) )
```

## Remove individuals
```{r}
which(bigBrowns$len==536)
bigBrowns[4,]
( bigBrowns2 <- bigBrowns[-4,] )
```




```{r echo=FALSE, results="hide", message=FALSE}
purl2("DataFrames2.Rmd",moreItems="knitr",out.dir="../Scripts",topnotes="Nunavut 6-9-Aug-16")
```
