---
title: "Summarization I"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot[RO,RE]{Ogle (Nunavut, 6-9 Aug 2016)}
- \fancyfoot[LE,LO]{data.frames II}
output: pdf_document
geometry: left=0.5in, right=0.5in, top=0.5in, bottom=0.75in
---

```{r echo=FALSE, results='hide'}
source("../knitr_setup.R")
```

----

# Preliminaries
## Load Necessary Packages
```{r results='hide', warning=FALSE, message=FALSE}
library(FSA)     # for filterD(), hist(), Summarize()
library(dplyr)   # for mutate(), group_by(), summarize()
library(plotrix)
```

## Load Data
```{r}
# Set your working directory to where your external data files (and scripts) are located.
setwd("C:/aaaWork/Web/GitHub/RcourseNunavut2016/Handouts")
dSC <- read.csv("SawyerCo_reduced.csv")
names(dSC)
LChip <- filterD(dSC,waterbody=="LAKE CHIPPEWA")
LChip_WAE <- filterD(LChip,species=="Walleye")
LChip_WAE <- mutate(LChip_WAE,sex=mapvalues(sex,from="",to="ND"),fyear=factor(year))
LChip_WAE11 <- filterD(LChip_WAE,year==2011)
```

----

# Univariate Summaries -- Categorical Variables
```{r}
( t_spec <- xtabs(~species,data=LChip))
( t_sex <- xtabs(~sex,data=LChip_WAE11) )
( tp_sex <- prop.table(t_sex)*100 )
```

```{r fig.show='hold'}
barplot(t_sex)  # Left
barplot(tp_sex,xlab="Sex",ylab="Percent of Sample",ylim=c(0,60),col="black")  # Right
```

# Univariate Summaries -- Quantitative Variables
```{r fig.show='hold'}
hist(~len,data=LChip_WAE11,xlab="Total Length (mm)",ylim=c(0,1000),w=10)  # Left
hist(~len,data=LChip_WAE11,xlab="Total Length (mm)",ylim=c(0,2500),breaks=seq(100,800,25))  # Right
```

```{r}
Summarize(~len,data=LChip_WAE11,digits=1)
```

# Univariate Summaries -- Quantitative Variables by Group
```{r fig.width=6, fig.height=4.5}
hist(len~fyear,data=LChip_WAE,w=10,same.ylim=FALSE)
```

```{r}
Summarize(len~fyear,data=LChip_WAE,digits=1)
```

```{r}
LChip_WAE <- group_by(LChip_WAE,year)
sum_LChip_WAE <- summarize(LChip_WAE,
                           n=n(),mn=mean(len,na.rm=TRUE),sd=sd(len,na.rm=TRUE),se=se(len,na.rm=TRUE),
                           lci=mn-qt(0.975,df=n-1)*se,uci=mn+qt(0.975,df=n-1)*se)
sum_LChip_WAE
```

```{r}
with(sum_LChip_WAE,plotCI(year,mn,li=lci,ui=uci,pch=19,cex=0.5,ylim=c(0,400),
                          xlab="Year",ylab="Mean Total Length (mm)"))
with(sum_LChip_WAE,lines(year,mn,col="gray70"))
```


```{r echo=FALSE, results="hide", message=FALSE}
purl2("Summarization1.Rmd",moreItems="knitr",out.dir="../Scripts",topnotes="Nunavut 6-9-Aug-16")
```
