---
title: "data.frames I - Walleye Exercise"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot[RO,RE]{Ogle (Nunavut, 6-9 Aug 2016)}
- \fancyfoot[LE,LO]{data.frames I Exercise}
output: pdf_document
geometry: left=0.5in, right=0.5in, top=0.5in, bottom=0.75in
---

```{r echo=FALSE, results='hide', message=FALSE}
showkey <- FALSE
source("../knitr_Ex_setup.R")
```
```{r message=FALSE, warning=FALSE}
library(FSA)
```

----

1. Load the `WalleyeErie2.csv` file into a data.frame object and answer the following questions.
```{r}
dWE <- read.csv("WalleyeErie2.csv")
str(dWE)
```
    a. How many variables are recorded in this data.frame?
```{r}
ncol(dWE)
```
    b. How many individuals are recorded in this data.frame?
```{r}
nrow(dWE)
```
    c. What is the name and data type for the fifth variable?
```{r}
names(dWE)[5]
class(dWE[,5])
```
    d. What is the name and data type for the second variable?  Does the data type make sense?
```{r}
names(dWE)[2]
class(dWE[,2])
```
    e. Demonstrate how to access all of the total length (`tl`) measurements.
```{r}
dWE$tl
```
    f. Demonstrate how to see the fifth total length measurement.
```{r}
dWE$tl[5]
```
    g. Demonstrate how to see the total length measurements for all fish captued in 2003.
```{r}
dWE$tl[dWE$year==2003]
```

----

```{r echo=FALSE, results="hide", message=FALSE}
purl2("DataFrames1.Rmd",moreItems=c("knitr","showkey"),topnotes="Nunavut 6-9-Aug-16")
```
