---
title: "Compare VBGFs"
subtitle: "Exercise - Walleye"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot[RO,RE]{Ogle (Nunavut, 6-9 Aug 2016)}
- \fancyfoot[LE,LO]{Compare VBGFs}
output: pdf_document
geometry: left=0.5in, right=0.5in, top=0.5in, bottom=0.75in
---

```{r echo=FALSE, results='hide', message=FALSE}
showkey <- FALSE
source("../knitr_Ex_setup.R")
```
```{r message=FALSE, warning=FALSE}
library(FSA)      # for filterD(), headtail(), col2rgbt(), vbFuns(), vbStart()
library(dplyr)    # for mutate(), select()
library(nlstools) # for nlsBoot()
```

----

1. Load the `WalleyeErie2.csv` file into a data.frame object and restrict the data to Walleye captured from location 1 in 2013.  Use these data for the following questions.
```{r}
dWE <- read.csv("WalleyeErie2.csv")
dWE_13 <- filterD(dWE,loc==1,year==2013)
```

    a. Plot length versus age with different colors or symbols for each sex.  Do you foresee any model fitting problems with these data?  Do you observe any possible differences in growth between the sexes?
```{r}
xlbl <- "Age (yrs)"
ylbl <- "Total Length (in)"
clr1 <- c("black","blue")
clr2 <- col2rgbt(clr1,1/5)

plot(tl~age,data=dWE_13,pch=19,col=clr2[sex],xlab=xlbl,ylab=ylbl)
```

    b. Fit the *additive* errors (i.e., no logarithms) typical VBGF where all parameters differ by sex.  Assess the assumptions from this model fit.
```{r fig.width=6}
( svOm <- vbStarts(tl~age,data=dWE_13) )
( svLKt <- Map(rep,svOm,c(2,2,2)) )
vbLKt <- tl~Linf[sex]*(1-exp(-K[sex]*(age-t0[sex])))
fitLKt <- nls(vbLKt,data=dWE_13,start=svLKt)
residPlot(fitLKt)
```

    c. Compute point and 95% confidence interval estimates for each parameter in the model where all parameters differ by sex.  Describe any problems that you encountered.
```{r eval=ifelse(showkey,TRUE,FALSE), error=TRUE}
bootLKt <- nlsBoot(fitLKt,niter=100)
cbind(Ests=coef(fitLKt),confint(fitLKt))
```

    d. Use either a likelihood ratio or extra sums-of-squares test to find the most parsimonius model that is a subset of the model fit above.  Summarize (in words) the results of your final model.
```{r message=FALSE}
vbOm <- tl~Linf*(1-exp(-K*(age-t0)))
fitOm <- nls(vbOm,data=dWE_13,start=svOm)

vbLK <- tl~Linf[sex]*(1-exp(-K[sex]*(age-t0)))
svLK <- Map(rep,svOm,c(2,2,1))
fitLK <- nls(vbLK,data=dWE_13,start=svLK)
vbLt <- tl~Linf[sex]*(1-exp(-K*(age-t0[sex])))
svLt <- Map(rep,svOm,c(2,1,2))
fitLt <- nls(vbLt,data=dWE_13,start=svLt)
vbKt <- tl~Linf*(1-exp(-K[sex]*(age-t0[sex])))
svKt <- Map(rep,svOm,c(1,2,2))
fitKt <- nls(vbKt,data=dWE_13,start=svKt)

vbL <- tl~Linf[sex]*(1-exp(-K*(age-t0)))
svL <- Map(rep,svOm,c(2,1,1))
fitL <- nls(vbL,data=dWE_13,start=svL)
vbK <- tl~Linf*(1-exp(-K[sex]*(age-t0)))
svK <- Map(rep,svOm,c(1,2,1))
fitK <- nls(vbK,data=dWE_13,start=svK)
vbt <- tl~Linf*(1-exp(-K*(age-t0[sex])))
svt <- Map(rep,svOm,c(1,1,2))
fitt <- nls(vbt,data=dWE_13,start=svt)

extraSS(fitOm,com=fitLKt,sim.name="{Omega}",com.name="{Linf,K,t0}")
extraSS(fitLK,fitLt,fitKt,com=fitLKt,com.name="{Linf,K,t0}",
        sim.names=c("{Linf,K}","{Linf,t0}","{K,t0}"))
extraSS(fitL,fitt,com=fitLt,com.name="{Linf,t0}",
        sim.names=c("{Linf}","{t0}"))

lrt(fitOm,com=fitLKt,sim.name="{Omega}",com.name="{Linf,K,t0}")
lrt(fitLK,fitLt,fitKt,com=fitLKt,com.name="{Linf,K,t0}",
    sim.names=c("{Linf,K}","{Linf,t0}","{K,t0}"))
lrt(fitL,fitt,com=fitLt,com.name="{Linf,t0}",
    sim.names=c("{Linf}","{t0}"))

summary(fitLt)
cbind(Ests=coef(fitLt),confint(fitLt))
```

    e. Fit the typical VBGF seperately to both sexes.  Compute point and 95% confidence interval estimates for each parameter in the separate models.  How do the point estimates from these separate models compare to the point estimates from the most complex model in #2 above?
```{r message=FALSE}
vb <- vbFuns("typical")

# females
fem <- filterD(dWE_13,sex=="female")
svf <- list(Linf=643,K=0.34,t0=-1.4)
fitf <- nls(tl~vb(age,Linf,K,t0),data=fem,start=svf)
# males
mal <- filterD(dWE_13,sex=="male")
svm <- list(Linf=567,K=0.34,t0=-1.9)
fitm <- nls(tl~vb(age,Linf,K,t0),data=mal,start=svm)

cbind(EstF=coef(fitf),confint(fitf),EstM=coef(fitm),confint(fitm))
cbind(Est=coef(fitLKt),confint(fitLKt))
```

    f. Construct a summary graphic that shows the growth trajectories superimposed on the observed data for both sexes.
```{r}
offset <- 0.08
# females
plot(tl~I(age-offset),data=fem,pch=19,col=clr2[1],ylim=c(0,660),xlim=c(-2,10),xlab=xlbl,ylab=ylbl)
curve(vb(x-offset,coef(fitf)),from=-2,to=10,col=clr1[1],lwd=2,add=TRUE)
# males
points(tl~I(age+offset),data=mal,pch=19,col=clr2[2])
curve(vb(x+offset,coef(fitm)),from=-2,to=10,col=clr1[2],lwd=2,add=TRUE)
legend("bottomright",levels(dWE_13$sex),pch=19,col=clr1,bty="n",cex=0.8)
```

----

2. [*Time Permitting*] Compare the fit of the typical VBGF between 2010 and 2013 for **male** Walleye captured in **location 1**.

```{r}
dWE_1013 <- filterD(dWE,loc==1,year %in% c(2010,2013))
dWE_1013 <- mutate(dWE_1013,fyear=factor(year))

vbOm <- tl~Linf*(1-exp(-K*(age-t0)))
svOm <- vbStarts(tl~age,data=dWE_1013)
fitOm <- nls(vbOm,data=dWE_1013,start=svOm)

svLKt <- Map(rep,svOm,c(2,2,2))
vbLKt <- tl~Linf[fyear]*(1-exp(-K[fyear]*(age-t0[fyear])))
fitLKt <- nls(vbLKt,data=dWE_1013,start=svLKt)

vbLK <- tl~Linf[fyear]*(1-exp(-K[fyear]*(age-t0)))
svLK <- Map(rep,svOm,c(2,2,1))
fitLK <- nls(vbLK,data=dWE_1013,start=svLK)
vbLt <- tl~Linf[fyear]*(1-exp(-K*(age-t0[fyear])))
svLt <- Map(rep,svOm,c(2,1,2))
fitLt <- nls(vbLt,data=dWE_1013,start=svLt)
vbKt <- tl~Linf*(1-exp(-K[fyear]*(age-t0[fyear])))
svKt <- Map(rep,svOm,c(1,2,2))
fitKt <- nls(vbKt,data=dWE_1013,start=svKt)

vbL <- tl~Linf[fyear]*(1-exp(-K*(age-t0)))
svL <- Map(rep,svOm,c(2,1,1))
fitL <- nls(vbL,data=dWE_1013,start=svL)
vbK <- tl~Linf*(1-exp(-K[fyear]*(age-t0)))
svK <- Map(rep,svOm,c(1,2,1))
fitK <- nls(vbK,data=dWE_1013,start=svK)
vbt <- tl~Linf*(1-exp(-K*(age-t0[fyear])))
svt <- Map(rep,svOm,c(1,1,2))
fitt <- nls(vbt,data=dWE_1013,start=svt)

extraSS(fitOm,com=fitLKt,sim.name="{Omega}",com.name="{Linf,K,t0}")
extraSS(fitLK,fitLt,fitKt,com=fitLKt,com.name="{Linf,K,t0}",
        sim.names=c("{Linf,K}","{Linf,t0}","{K,t0}"))
extraSS(fitK,fitt,com=fitLt,com.name="{K,t0}",
        sim.names=c("{K}","{t0}"))

# 2010
plot(tl~I(age-offset),data=filterD(dWE_1013,year==2010),pch=19,col=clr2[1],
     ylim=c(0,700),xlim=c(-2,16),xlab=xlbl,ylab=ylbl)
curve(vb(x-offset,coef(fitLKt)[c(1,3,5)]),from=-2,to=16,col=clr1[1],lwd=2,add=TRUE)
# males
points(tl~I(age+offset),data=filterD(dWE_1013,year==2013),pch=19,col=clr2[2])
curve(vb(x+offset,coef(fitLKt)[c(2,4,6)]),from=-2,to=16,col=clr1[2],lwd=2,add=TRUE)
legend("bottomright",levels(dWE_1013$fyear),pch=19,col=clr1,bty="n",cex=0.8)
```


----

```{r echo=FALSE, results="hide", message=FALSE}
purl2("VBGF2.Rmd",moreItems=c("knitr","showkey","seed"),topnotes="Nunavut 6-9-Aug-16")
```
