---
title: "data.frames I - Nunavut Exercise"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot[RO,RE]{Ogle (Nunavut, 6-9 Aug 2016)}
- \fancyfoot[LE,LO]{data.frames I Exercise}
output: pdf_document
geometry: left=0.5in, right=0.5in, top=0.5in, bottom=0.75in
---

```{r echo=FALSE, results='hide', message=FALSE}
showkey <- FALSE
source("../knitr_Ex_setup.R")
```
```{r message=FALSE, warning=FALSE}
library(FSA)
library(dplyr)
library(readxl)
```

----

1. Create a "metadata" CSV file that corresponds to the `PG008_original.xlsx` data file.  [Note that the variables in this file are *slightly* different than the variables in the data file used in the handout.  I suggest you start with the metadata file used in the handout and modify it to match the variales in the `PG008_original.xlsx` Excel file.]  Save this file in the same directory as the corresponding data file.

1. Load the `PG008_original.xlsx` file into a data.frame object and change the variable names and types to more readily useable.
```{r message=FALSE, warning=FALSE}
source("PG008_readdata.R")
str(dNU)
```

    a. How many variables are recorded in this data.frame?
```{r}
ncol(dNU)
```
    b. How many individuals are recorded in this data.frame?
```{r}
nrow(dNU)
```
    c. What is the name and data type for the fifth variable?  Does the data type make sense?  Does the number of levels for this variable make sense?
```{r}
names(dNU)[5]
class(dNU[,5])
```
    d. What is the name and data type for the second variable?
```{r}
names(dNU)[2]
class(dNU[,2])
```
    e. Demonstrate how to access all of the fork length (`fl`) measurements.
```{r}
dNU$fl
```
    f. Demonstrate how to see the fifth fork length measurement.
```{r}
dNU$fl[5]
```
    g. Demonstrate how to see the fork length measurements for all fish captued in 2002.
```{r}
dNU$fl[dNU$year==2002]
```

----

```{r echo=FALSE, results="hide", message=FALSE}
purl2("DataFrames1.Rmd",moreItems=c("knitr","showkey"),topnotes="Nunavut 6-9-Aug-16")
```
